version: '3.8'

services:
  yolo-api:
    # image: DCharles403/yolo-flask-api:latest
    # container_name: yolo-api
    build:
      context: ./yolo_api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  streamlit-app:
    # image: DCharles403/yolo-streamlit-app:latest
    # container_name: streamlit-app
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    # depends_on:
    #   - yolo-api # wait for flask api to start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
