AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EC2 instance with security groups for Flask and Streamlit and budget alerts for EC2 instance

Parameters:
  KeyName:
    Type: String
    Description: Name of the EC2 key pair

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  AWSRegion:
    Type: String
    Default: us-east-2
    Description: AWS region for the resources

  # Find Ubuntu AMI
  # UbuntuAMI:
  #   Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  #   Default: /aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64

  UbuntuAMI:
      Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
      Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  AlertEmail:
    Type: String
    Description: Email address for budget notifications

  VPC:
    Type: String
    Description: VPC ID for security groups

Resources:
  # Security Group for EC2
  StreamlitFlaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group to allow inbound SCP, Flask ML API, and Streamlit
      SecurityGroupIngress:
        - Description: Inbound SCP
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - Description: Inbound Yolo Flask API
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - Description: Inbound Streamlit application
          IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          # Value: streamlit_flask_security_group
          Value: streamlit_flask_security_group2

  StreamlitFlaskInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref UbuntuAMI
      SecurityGroupIds:
        - !Ref StreamlitFlaskSecurityGroup
      UserData: 
        Fn::Base64: !Sub |      
          #!/bin/bash

          sudo yum update -y 

          sudo yum install docker -y

          sudo systemctl start docker

          sudo yum install curl -y

          sudo curl -SL
          https://github.com/docker/compose/releases/download/v2.29.6/docker-co\
          mpose-linux-x86_64 -o /usr/local/bin/docker-compose

          sudo chmod +x /usr/local/bin/docker-compose

          sudo yum install git -y

          sudo yum install make -y

          sudo usermod -aG docker $USER

          newgrp docker\n

      Tags:
        - Key: Name
          Value: streamlit_flask_ec2

  EC2Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: budget-ec2-monthly
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: 5
          Unit: USD
        TimePeriod:
          Start: 1707609600 #2024-02-11T00:00:00Z
          End: 3706473600 # 2087-06-15T00:00:00Z
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail

Outputs:
  InstanceId:
    Description: Instance ID of the EC2
    Value: !Ref StreamlitFlaskInstance

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref StreamlitFlaskSecurityGroup

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt StreamlitFlaskInstance.PublicIp